name: Build

on:
  push:
    branches:
      - master
      - develop
      - release

jobs:
  build:
    name: awspec
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Checkout
      uses: actions/checkout@v2   

    - name: RSpec
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    - run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec kitchen test